services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "${QDRANT_REST_HOST_PORT:-6333}:6333"
      - "${QDRANT_GRPC_HOST_PORT:-6334}:6334"
    volumes:
      - ~/.qdrant:/qdrant/storage