services:
  langwatch:
    image: langwatch/langwatch:latest
    environment:
      SKIP_ENV_VALIDATION: true
      DISABLE_PII_REDACTION: true
      DATABASE_URL: postgresql://prisma:prisma@langwatch-postgres:5432/mydb?schema=mydb
      ELASTICSEARCH_NODE_URL: http://langwatch-opensearch:9200
      IS_OPENSEARCH: true
      REDIS_URL: redis://langwatch-redis:6379
      LANGWATCH_NLP_SERVICE: http://langwatch_nlp:8080
      LANGEVALS_ENDPOINT: http://langevals:8000
    env_file:
      - .env
    pull_policy: always
    ports:
      - "${LANGWATCH_HOST_PORT:-5560}:5560"
    depends_on:
      langwatch-postgres:
        condition: service_healthy
      langwatch-redis:
        condition: service_healthy
      langwatch-opensearch:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "${CPU_LIMIT:-2.0}"
          memory: "${MEMORY_LIMIT:-2048M}"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:${LANGWATCH_HOST_PORT:-5560} || exit 1"]
      interval: 15s
      timeout: 15s
      retries: 3
      start_period: 150s

  langwatch_nlp:
    image: langwatch/langwatch_nlp:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    pull_policy: always
    environment:
      - LANGWATCH_ENDPOINT=http://langwatch:5560
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  langevals:
    image: langwatch/langevals:latest
    ports:
      - "8000:8000"
    restart: always
    pull_policy: always
    environment:
      - DISABLE_EVALUATORS_PRELOAD=true
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  langwatch-postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  langwatch-redis:
    image: redis:alpine
    ports:
      - "6377:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"

  langwatch-opensearch:
    image: opensearchproject/opensearch:2.17.1
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      # Disable specific plugins
      - "plugins.anomaly_detection.enabled=false"
      - "plugins.flow_framework.enabled=false"
      - "plugins.security_analytics.ioc_finding_enabled=false"
      - "plugins.sql.enabled=false"
      - "plugins.rollup.enabled=false"
      # Performance settings
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m -XX:+UseG1GC -XX:-UseSerialGC -XX:G1ReservePercent=25 -XX:+AlwaysPreTouch -XX:InitiatingHeapOccupancyPercent=30"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "bootstrap.memory_lock=false" # Changed from true to avoid memory locking warnings
      # Disk settings
      - "cluster.routing.allocation.disk.watermark.low=95%"
      - "cluster.routing.allocation.disk.watermark.high=96%"
      - "cluster.routing.allocation.disk.watermark.flood_stage=97%"
      - "cluster.info.update.interval=1m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Some-random-password-which-is-greater-than-16-chars-long~
      # System limits
      - "node.store.allow_mmap=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 90s
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1024M"
    restart: always

volumes:
  db-data:
  redis-data:
  opensearch-data: