services:
  langflow:
    build: .
    ports:
      - "${HOST_PORT:-7860}:7860"
    environment:
      - LANGFLOW_DATABASE_URL=sqlite:///./langflow/langflow.db
    volumes:
      - ~/.langflow:/app/langflow
    platform: linux/arm64/v8
    deploy:
      resources:
        limits:
          cpus: "${CPU_LIMIT:-0.5}"
          memory: "${MEMORY_LIMIT:-1024M}"
    healthcheck:
      test: curl -f http://localhost:${HOST_PORT} || exit 1
      interval: 2s
      timeout: 15s
      retries: 5
      start_period: 50s
